# These are supported funding model platforms

github: [AbhayAppDeveloper]
open_collective: # Replace with a single Open Collective username
ko_fi: abhaykorat
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/AbhayAppDeveloper
custom: # Replace with a single custom sponsorship URL